openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /api/garbage-posts:
    get:
      tags:
        - public
      summary: get public post list
      parameters:
        - name: key_word
          in: query
          required: false
          type: string
          description: key word for search post by description
      responses:
        '200':
          description: Pagination list of public posts
        '500': 
          description: Failed to fetch garbage posts
  /api/login:
    post:
      tags:
        - users
      summary: Login to the user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: user email
                password:
                  type: string
                  format: password
                  description: user password
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
        '401':
          description: Login failed, wrong login information
